version: "3.9"

volumes:
  kafka-data: 
    driver: local
  neo4j-data: 
    driver: local
  timescaledb-data: 
    driver: local
  test_data_loader-data: 
    driver: local
  spark-data:
    driver: local
networks:
  crit_infra_net:
    driver: bridge
services:
    cis-spark-master:
      image: bitnami/spark:3.5
      container_name: cis-spark-master
      restart: unless-stopped
      environment:
        SPARK_MODE: "master"
      ports:
        - "8080:8080"
        - "7077:7077"
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/bitnami
        - ./Logs/spark:/logs
        - ./data:/data
    cis_spark_worker:
      image: bitnami/spark:3.5
      container_name: cis_spark_worker
      restart: unless-stopped
      environment:
        SPARK_MODE: "worker"
        SPARK_MASTER_URL: "spark://cis-spark-master:7077"
        SPARK_WORKER_MEMORY: "16G"
        SPARK_WORKER_CORES: "8"
      ports:
        - "8089:8081"
      depends_on:
        - cis-spark-master
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/bitnami
        - ./Logs/spark:/logs
        - ./data:/data
    cis_load_bigdata:
      build: services/spark
      container_name: cis_load_bigdata
      restart: "no"
      depends_on:
        - cis-spark-master
        - cis_spark_worker
        - cis_kafka
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/bitnami
        - ./Logs/spark:/logs
        - ./data:/data
        - ./services/spark/data_scripts:/data_scripts
      environment:
        HOME: "/tmp"
        USER: "spark"
        HADOOP_USER_NAME: "spark"
        SPARK_SUBMIT_OPTS: "-Dspark.jars.ivy=/tmp/.ivy2 -Duser.home=/tmp -Duser.name=spark"
        SPARK_MASTER_URL: "spark://cis-spark-master:7077"
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_PHYS_TOPIC: "Data.Raw.Physical"
        KAFKA_SCADA_TOPIC: "Data.Raw.Scada"
        PHYS_DATA_DIR: "file:///data/testbed_system_1/Physical"
        SCADA_DATA_DIR: "file:///data/testbed_system_1/Network/csv"
      entrypoint: 
        - "/opt/bitnami/spark/bin/spark-submit"
        - "--master"
        - "spark://cis-spark-master:7077"
        - "--conf"
        - "spark.hadoop.hadoop.security.authentication=simple"
        - "--conf"
        - "spark.authenticate=false"
        - "--conf"
        - "spark.hadoop.fs.defaultFS=file:///"
        - "--conf"
        - "spark.hadoop.fs.file.impl=org.apache.hadoop.fs.LocalFileSystem"
        - "--conf"
        - "spark.driver.extraJavaOptions=-Duser.name=spark -Duser.home=/tmp"
        - "--conf"
        - "spark.executor.extraJavaOptions=-Duser.name=spark -Duser.home=/tmp"
        - "--conf"
        - "spark.jars.ivy=/tmp/.ivy2"
        - "--conf"
        - "spark.executor.instances=2"
        - "--conf"
        - "spark.executor.memory=8g"
        - "--conf"
        - "spark.executor.cores=4"
        - "--conf"
        - "spark.driver.memory=8g"
        - "--packages"
        - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"
        - "/data_scripts/load_bigdata.py"


    cis_kafka:
      image: bitnami/kafka:latest
      container_name: cis_kafka      
      restart: unless-stopped
      ports:
        - "9092:9092"
      healthcheck:
        test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "cis_kafka:9092"]
        interval: 30s
        timeout: 10s
        retries: 5
      environment:        
          KAFKA_ENABLE_KRAFT: "yes"
          KAFKA_CFG_NODE_ID: "1"
          KAFKA_CFG_PROCESS_ROLES: "broker,controller"
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@cis_kafka:9093"
          
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://cis_kafka:9092"
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

          KAFKA_HEAP_OPTIONS: "-Xms6g -Xmx6g"
          KAFKA_CFG_NUM_NETWORK_THREADS: "6"
          KAFKA_CFG_NUM_IO_THREADS: "16"
          KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: "1048576"
          KAFKA_CFG_MESSAGE_MAX_BYTES: "2000000"
          KAFKA_CFG_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: "1048576"

          KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
          KAFKA_CFG_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"

          KAFKA_CREATE_TOPICS: "Data.Raw.Physical:1:16,Data.Raw.Scada:1:16,Data.Error:1:1,Data.Graphs:1:1, Anomaly.Predict:1:1,Anomaly.Alerts:1:1"          
      volumes:
        - "kafka-data:/bitnami"
      networks:
        crit_infra_net:
          aliases:
            - cis_kafka
            - kafka    
    cis_neo4j:
      image: neo4j:4.4.0-enterprise
      container_name: cis_neo4j
      hostname: cis_neo4j
      restart: always
      ports:
        - "7485:7485"
        - "7698:7698"
      environment:
        NEO4J_AUTH: "neo4j/changeme" # Default password if not set in env
        NEO4J_apoc_trigger_enabled: "true"
        NEO4JLABS_PLUGINS: '["apoc", "n10s"]' # Include n10s (Neosemantics) plugin
        NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes' # Required if using Enterprise version
        NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
        NEO4J_apoc_import_file_enabled: "true"
        NEO4J_apoc_initializer_cypher: "CALL apoc.cypher.runFiles(['file:///init.cypher'])"
        NEO4J_dbms_jvm_additional: "-XX:-UseContainerSupport"
        NEO4J_dbms_connector_http_listen__address: ":7485"
        NEO4J_dbms_connector_bolt_listen__address: ":7698"
        NEO4J_dbms_connector_http_advertised_address: "localhost:7485"
        NEO4J_dbms_connector_bolt_advertised_address: "localhost:7698"
      volumes:
        - neo4j-data:/data        
        - ./services/neo4j/import:/var/lib/neo4j/import # Mount the import directory for initial cypher scripts
      networks:
        - crit_infra_net
    cis_timescaledb:
      image: timescale/timescaledb:latest-pg14
      container_name: cis_timescaledb
      hostname: timescaledb
      restart: unless-stopped
      ports:
        - "5445:5432"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "anomalydetection"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d anomalydetection"]
        interval: 15s
        timeout: 5s
        retries: 15
      volumes:
        - timescaledb-data:/var/lib/postgresql/data
      networks:
        - crit_infra_net
      
    cis_test_data_loader:
      build: services/test_data_load
      container_name: cis_test_data_load
      restart: unless-stopped
      ports:
        - "8090:8090"
      depends_on:
        cis_kafka:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_PHYS_TOPIC: "Data.Raw.Physical"
        KAFKA_SCADA_TOPIC: "Data.Raw.Scada"
        KAFKA_GENERATE_GRAPH_TOPIC: "Data.Graphs"
        DATA_DIR: "/app/data"
        SCHEMA_DIR: "/app/schemas"
      volumes:
        - ./data:/app/data
        - ./schemas:/app/schemas 
      networks:
        - crit_infra_net
    cis_dash_app:
      build: dash_app
      container_name: cis_dash_app
      restart: unless-stopped
      ports:
        - "8050:8050"
      depends_on:
        - cis_timescaledb
        - cis_neo4j
      environment:
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
        NEO4J_HOST: "cis_neo4j"
        NEO4J_PORT: 7687
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "gr@ph$Rfun!"
      networks:
        - crit_infra_net
    cis_raw_network_consumer:
      build: .
      container_name: cis_raw_network_consumer
      restart: unless-stopped
      command: python src/data_ingestion/raw_network_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy            
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_TOPIC: "Data.Raw.Scada"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_raw_physical_consumer:
      build: .
      container_name: cis_raw_physical_consumer
      restart: unless-stopped
      command: python src/data_ingestion/raw_physical_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy          
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_TOPIC: "Data.Raw.Physical"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_data_error_consumer:
      build: .
      container_name: cis_data_error_consumer
      restart: unless-stopped
      command: python src/data_ingestion/data_error_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy          
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_DATA_ERROR_TOPIC: "Data.Error"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_graph_generator_consumer:
      build: .
      container_name: cis_graph_generator_consumer
      restart: unless-stopped
      command: python src/graph_generation/graph_generator_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy          
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_TOPIC: "Data.Graphs"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
        NEO4J_HOST: "cis_neo4j"
        NEO4J_PORT: 7687
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "gr@ph$Rfun!"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_anomaly_detector_consumer:
      build: .
      container_name: cis_anomaly_detector_consumer
      restart: unless-stopped
      command: python src/anomaly_detection/anomaly_detection_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy          
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_TOPIC: "Data.Graphs"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
        NEO4J_HOST: "cis_neo4j"
        NEO4J_PORT: 7687
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "gr@ph$Rfun!"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_alerts_consumer:
      build: .
      container_name: cis_alerts_consumer
      restart: unless-stopped
      command: python src/alerts/alerts_consumer.py
      depends_on:
        cis_kafka:
          condition: service_healthy          
        cis_timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis_kafka:9092"
        KAFKA_TOPIC: "Anomaly.Alerts"
        TIMESCALEDB_HOST: timescaledb
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
        NEO4J_HOST: "cis_neo4j"
        NEO4J_PORT: 7687
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "gr@ph$Rfun!"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis_init_timescaledb:
      build: services/postgres
      container_name: cis_init_timescaledb
      depends_on:
        cis_timescaledb:
          condition: service_healthy
      environment:
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
      networks:
        - crit_infra_net
      command: bash -c "python init_db.py && python load_testbed_metadata.py"
      restart: "no"
      # This service runs once to initialize the database and then exits
      