volumes:
  kafka-data: 
    driver: local
  neo4j-data: 
    driver: local
  timescaledb-data: 
    driver: local
  test_data_loader-data: 
    driver: local
  spark-data:
    driver: local
  rag-anything-data:
    driver: local
  ollama-data:
    driver: local
networks:
  crit_infra_net:
    driver: bridge
services:
    cis-spark-master:
      image: apache/spark:3.5.1      
      container_name: cis-spark-master
      profiles: [etl,data_load]
      restart: unless-stopped
      command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
      environment:
        SPARK_MODE: "master"
        SPARK_MASTER_HOST: "cis-spark-master"
        SPARK_MASTER_PORT: 7077
        SPARK_MASTER_WEBUI_PORT: 8080
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      ports:
        - "8080:8080"
        - "7077:7077"
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/opt/spark/work-dir
        - ./Logs/spark:/logs
        - ./data:/data
    cis-spark-worker:
      image: apache/spark:3.5.1      
      container_name: cis-spark-worker
      profiles: [etl,data_load]
      restart: unless-stopped
      command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://cis-spark-master:7077"]
      environment:
        #TODO: Change as necessary depending on host machine available resources
        SPARK_MODE: "worker"
        SPARK_MASTER_URL: "spark://cis-spark-master:7077"
        SPARK_WORKER_MEMORY: "16G"
        SPARK_WORKER_CORES: "8"
        SPARK_WORKER_WEBUI_PORT: 8081
      ports:
        - "8089:8081"
      depends_on:
        cis-spark-master:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/opt/spark/work-dir
        - ./Logs/spark:/logs
        - ./data:/data
    cis-load-bigdata:
      build: services/spark
      container_name: cis-load-bigdata
      profiles: [data_load]
      restart: "no"
      depends_on:
        - cis-spark-master
        - cis-spark-worker
        - cis-kafka
      networks:
        - crit_infra_net
      volumes:
        - spark-data:/opt/spark/work-dir
        - ./Logs/spark:/logs
        - ./services/spark/data_scripts:/data_scripts  
        - ./data:/data     
      environment:
        HOME: "/tmp"
        USER: "spark"
        HADOOP_USER_NAME: "spark"
        SPARK_SUBMIT_OPTS: "-Dspark.jars.ivy=/tmp/.ivy2 -Duser.home=/tmp -Duser.name=spark"
        SPARK_MASTER_URL: "spark://cis-spark-master:7077"
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_PHYS_TOPIC: "Data.Raw.Physical"
        KAFKA_SCADA_TOPIC: "Data.Raw.Scada"
        PHYS_UTF16_DATA_DIR: "/data/testbed_system_1/Physical/utf16"
        PHYS_UTF16_DATA_DEST_DIR: "/data/testbed_system_1/Physical"
        PHYS_DATA_DIR: "file:///data/testbed_system_1/Physical"
        SCADA_DATA_DIR: "file:///data/testbed_system_1/Network/csv"
      entrypoint: 
        - "/opt/spark/bin/spark-submit"
        - "--master"
        - "spark://cis-spark-master:7077"
        - "--conf"
        - "spark.hadoop.hadoop.security.authentication=simple"
        - "--conf"
        - "spark.authenticate=false"
        - "--conf"
        - "spark.hadoop.fs.defaultFS=file:///"
        - "--conf"
        - "spark.hadoop.fs.file.impl=org.apache.hadoop.fs.LocalFileSystem"
        - "--conf"
        - "spark.driver.extraJavaOptions=-Duser.name=spark -Duser.home=/tmp"
        - "--conf"
        - "spark.executor.extraJavaOptions=-Duser.name=spark -Duser.home=/tmp"
        - "--conf"
        - "spark.jars.ivy=/tmp/.ivy2"
        #TODO: Change as necessary depending on host machine available resources
        - "--conf"
        - "spark.executor.instances=2"
        - "--conf"
        - "spark.executor.memory=8g"
        - "--conf"
        - "spark.executor.cores=4"
        - "--conf"
        - "spark.driver.memory=8g"
        - "--packages"
        - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"
        - "/data_scripts/load_bigdata.py"
    cis-ollama:
      image: ollama/ollama:latest
      container_name: cis-ollama
      profiles: [frontend_ai]
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "ollama", "list"]
        interval: 15s
        timeout: 10s
        retries: 10
      ports:
        - "11434:11434"
      volumes:
        - ollama-data:/var/lib/ollama
      networks:
        - crit_infra_net
    cis-ollama-pull-models:
      image: ollama/ollama:latest
      container_name: cis-ollama-pull-models
      profiles: [frontend_ai]
      restart: "no"
      depends_on:
        cis-ollama:
          condition: service_healthy
      environment:
        OLLAMA_HOST: http://cis-ollama:11434
      networks:
        - crit_infra_net  
      entrypoint: 
        # Pull models on startup, change as necessary
        - "/bin/sh"
        - "-lc"
        - "ollama pull llama3.1:8b && ollama pull bge-m3"
    cis-kafka:
      image: apache/kafka:latest
      container_name: cis-kafka  
      profiles: [etl, data_load, machine_learning]
      restart: unless-stopped
      ports:
        - "29092:29092"
      healthcheck:
        test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:29092"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s
      environment:                  
          KAFKA_NODE_ID: "1"
          KAFKA_PROCESS_ROLES: "broker,controller"
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@cis-kafka:9093"
          
          KAFKA_LISTENERS: "PLAINTEXT_HOST://:29092,PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://cis-kafka:9092,PLAINTEXT_HOST://localhost:29092"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

          #TODO: Change as necessary depending on host machine available resources
          KAFKA_HEAP_OPTS: "-Xms6g -Xmx6g"
          KAFKA_NUM_NETWORK_THREADS: "6"
          KAFKA_NUM_IO_THREADS: "16"
          KAFKA_SOCKET_SEND_BUFFER_BYTES: "1048576"
          KAFKA_MESSAGE_MAX_BYTES: "2000000"
          KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: "1048576"

          KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      volumes:
        - "kafka-data:/var/lib/kafka/data"
      networks:
        crit_infra_net:
          aliases:
            - cis-kafka
            - kafka    
    cis-kafka-init-topics:
      image: apache/kafka:latest
      container_name: cis-kafka-init-topics
      profiles: [etl, data_load, machine_learning]
      restart: "no"
      depends_on:
        cis-kafka:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
      networks:
        - crit_infra_net
      command: >
        bash -c "
          echo 'Waiting for Kafka to be ready...'
          until /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server cis-kafka:9092; do
            echo '... still waiting for Kafka';
            sleep 2;
          done;
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Data.Raw.Physical --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 16 --replication-factor 1 &&
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Data.Raw.Scada --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 16 --replication-factor 1 &&
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Data.Error --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 1 --replication-factor 1 &&
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Anomaly.Predict --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 16 --replication-factor 1 &&
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Data.Graphs --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 16 --replication-factor 1 &&
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic Anomaly.Alerts --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --partitions 1 --replication-factor 1
        "
    cis-neo4j:
      image: neo4j:4.4.0-enterprise
      container_name: cis-neo4j
      # Core infrastructure service, always active
      hostname: cis-neo4j
      restart: unless-stopped
      ports:
        - "7485:7485"
        - "7698:7698"
      environment:
        NEO4J_AUTH: "neo4j/changeme" # Default password if not set in env
        NEO4J_apoc_trigger_enabled: "true"
        NEO4J_apoc_export_file_enabled: "true"
        NEO4JLABS_PLUGINS: '["apoc", "n10s"]' # Include n10s (Neosemantics) plugin
        NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes' # Required if using Enterprise version
        NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
        NEO4J_apoc_import_file_enabled: "true"
        NEO4J_apoc_import_file_use_neo4j_config: "true"
        NEO4J_dbms_security_allow_csv_import_from_file_urls: "true"
        NEO4J_apoc_initializer_cypher: "CALL apoc.cypher.runFiles(['file:///init.cypher'])"
        #NEO4J_dbms_memory_heap_initial__size: "8G"
        #NEO4J_dbms_memory_heap_max__size: "8G"
        #NEO4J_dbms_memory_pagecache_size: "4G"
        NEO4J_dbms_jvm_additional: >-
          -XX:+UseContainerSupport
        NEO4J_dbms_connector_http_listen__address: ":7485"
        NEO4J_dbms_connector_bolt_listen__address: ":7698"
        NEO4J_dbms_connector_http_advertised_address: "localhost:7485"
        NEO4J_dbms_connector_bolt_advertised_address: "localhost:7698"        
        NEO4J_apoc_jdbc_postgres_url: >
          jdbc:postgresql://timescaledb:5432/?user=&password=password&sslmode=disable
      volumes:
        - neo4j-data:/data   
        - ./services/neo4j/plugins:/var/lib/neo4j/plugins # Mount the plugins directory     
        - ./services/neo4j/import:/var/lib/neo4j/import # Mount the import directory for initial cypher scripts        
      networks:
        - crit_infra_net
    cis-timescaledb:
      image: timescale/timescaledb:latest-pg14
      container_name: cis-timescaledb
      # Core infrastructure service, always active
      hostname: timescaledb
      restart: unless-stopped
      ports:
        - "5445:5432"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "anomalydetection"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d anomalydetection"]
        interval: 15s
        timeout: 5s
        retries: 15
      volumes:
        - timescaledb-data:/var/lib/postgresql/data
      networks:
        - crit_infra_net
        
    cis-rag-anything:
      build: services/rag_anything
      container_name: cis-rag-anything
      profiles: [frontend_ai]
      restart: unless-stopped
      ports:
        - "8000:8000"
      environment:
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
        NEO4J_URI: "bolt://cis-neo4j:7698"
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "changeme"        
        OPENAI_MODEL: "llama3.1:8b"
        OPENAI_EMBEDDING_MODEL: "bge-m3"
        RAG_SECRETS_FILE: "run/secrets/rag_anything"
        RAG_WORKING_DIR: "/app/data/rag_storage"
        RAG_KB_DIR: "/app/kb"
        RAG_OUTPUT_DIR: "/app/data/output"
        OPENAI_BASE_URL: "http://cis-ollama:11434/v1"
        OPENAI_API_KEY: "ollama"
      depends_on:
        cis-timescaledb:
          condition: service_healthy
      networks:
        - crit_infra_net
      secrets:
        - rag_anything
      volumes:
        - rag-anything-data:/app/data
        - ./schemas:/app/schemas
    cis-test-data-loader:
      build: services/test_data_load
      container_name: cis-test-data-load
      profiles: [etl, data_load, machine_learning]
      restart: unless-stopped
      ports:
        - "8090:8090"
      depends_on:
        cis-kafka:
          condition: service_healthy
      environment:
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PG_MIN_SIZE: 1
        PG_MAX_SIZE: 5
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_PHYS_TOPIC: "Data.Raw.Physical"
        KAFKA_SCADA_TOPIC: "Data.Raw.Scada"
        KAFKA_ANOMALY_TOPIC: "Anomaly.Predict"
        KAFKA_GENERATE_GRAPH_TOPIC: "Data.Graphs"
        DATA_DIR: "/app/exports/data"
        SCHEMA_DIR: "/app/schemas"
      volumes:
        - ./data:/app/data
        - ./schemas:/app/schemas 
        - ./exports:/app/exports
        - ./src/repositories:/app/repositories
        - ./src/factories:/app/factories
        - ./src/models:/app/models
        - ./src/xai:/app/xai
      networks:
        - crit_infra_net
    cis-dashboard-app:
      build: dashboard_app
      container_name: cis-dashboard-app
      profiles: [frontend,frontend_ai]
      restart: unless-stopped
      ports:
        - "8050:8050"
      depends_on:
        - cis-timescaledb
        - cis-neo4j
      networks:
        - crit_infra_net
    cis-raw-network-consumer:
      build: ./src/data_ingestion
      container_name: cis-raw-network-consumer
      profiles: [etl,data_load]
      restart: unless-stopped
      command: python raw_network_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy            
        cis-timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_TOPIC: "Data.Raw.Scada"
        KAFKA_ERROR_TOPIC: "Data.Error"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
        PG_TABLE: "scada_raw"
        PG_STAGE_TABLE: "scada_staging"
        BATCH_SIZE: 3000
        LINGER_MS: 200
        MAX_RECORDS: 10000
        SCHEMA_DIR: 'app/schemas'
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
        - ./schemas:/app/schemas
    cis-raw-physical-consumer:
      build: ./src/data_ingestion
      container_name: cis-raw-physical-consumer      
      profiles: [etl,data_load]
      restart: unless-stopped
      command: python raw_physical_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy          
        cis-timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_TOPIC: "Data.Raw.Physical"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
        PG_TABLE: "phys_raw"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
        - ./schemas:/app/schemas
    cis-data-error-consumer:
      build: .
      container_name: cis-data-error-consumer
      profiles: [etl, data_load, machine_learning]
      restart: unless-stopped
      command: python src/data_ingestion/data_error_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy          
        cis-timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_DATA_ERROR_TOPIC: "Data.Error"
        TIMESCALEDB_HOST: "timescaledb"
        TIMESCALEDB_PORT: 5432
        TIMESCALEDB_DB: "anomalydetection"
        TIMESCALEDB_USER: "postgres"
        TIMESCALEDB_PASSWORD: "password"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
    cis-graph-generator-consumer:
      build: ./src/knowledge_graphs
      container_name: cis-graph-generator-consumer
      profiles: [etl,data_load]
      restart: unless-stopped
      command: python graph_generator_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy          
        cis-timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_TOPIC: "Data.Graphs"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PG_MIN_SIZE: 1
        PG_MAX_SIZE: 5
        NEO4J_URI: "bolt://cis-neo4j:7698"
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "changeme"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
        - ./schemas:/app/schemas
        - ./src/factories:/app/factories
        - ./src/repositories:/app/repositories
    cis-anomaly-detector-consumer:
      build: ./src/anomalies
      container_name: cis-anomaly-detector-consumer
      profiles: [machine_learning]
      restart: unless-stopped
      command: python3 anomaly_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy          
        cis-timescaledb:
          condition: service_healthy
      gpus: all
      environment:
        NVIDIA_VISIBLE_DEVICES: "all"
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_TOPIC: "Anomaly.Predict"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PG_MIN_SIZE: 1
        PG_MAX_SIZE: 5
        NEO4J_URI: "bolt://cis-neo4j:7698"
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "changeme"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
        - ./schemas:/app/schemas
        - ./src/factories:/app/factories
        - ./src/repositories:/app/repositories
        - './src/models:/app/models'
        - './src/xai:/app/xai'
        - './exports:/app/exports'        
    cis-alerts-consumer:
      build: ./src/alerts
      container_name: cis-alerts-consumer
      profiles: [machine_learning]
      restart: unless-stopped
      command: python alerts_consumer.py
      depends_on:
        cis-kafka:
          condition: service_healthy          
        cis-timescaledb:
          condition: service_healthy
      environment:
        KAFKA_BOOTSTRAP_SERVERS: "cis-kafka:9092"
        KAFKA_TOPIC: "Anomaly.Alerts"
        PG_DSN: "postgresql://postgres:password@timescaledb:5432/anomalydetection?sslmode=disable"
        PG_MIN_SIZE: 1
        PG_MAX_SIZE: 5
        NEO4J_URI: "bolt://cis-neo4j:7698"
        NEO4J_USER: "neo4j"
        NEO4J_PASSWORD: "changeme"
      networks:
        - crit_infra_net
      volumes:
        - ./Logs/kafka:/app/logs
        - ./schemas:/app/schemas
        - ./src/factories:/app/factories
        - ./src/repositories:/app/repositories
    cis-init-timescaledb:
      build: services/postgres
      container_name: cis-init-timescaledb
      # Core process helper service, always active
      depends_on:
        cis-timescaledb:
          condition: service_healthy
      environment:
        PGHOST: timescaledb
        PGPORT: 5432
        PGUSER: "postgres"
        PGPASSWORD: "password"
        PGDATABASE: "anomalydetection"
        PGSSLMODE: "disable"
      networks:
        - crit_infra_net
      command: bash -c "python init_db.py && python load_testbed_metadata.py"
      restart: "no"
      # This service runs once to initialize the database and then exits
      
secrets:
  rag_anything:
    file: ragAnythingSecrets.json