
from datetime import datetime
from pydantic import BaseModel, Field
from typing import Optional

class ScadaAggregate(BaseModel):
    bucket: datetime = Field(..., description="Start time of the aggregation bucket")
    duration: Optional[int] = Field(..., description="Duration of the aggregation bucket in seconds")
    system_id: str = Field(..., description="Identifier for the system")
    protocol: str = Field(..., description="Network protocol used")
    avg_size: float = Field(..., description="Average size of packets in the bucket")
    source_total_packets: int = Field(..., description="Total packets sent from source")
    destination_total_packets: int = Field(..., description="Total packets sent to destination")
    min_size: int = Field(..., description="Minimum packet size in the bucket")
    max_size: int = Field(..., description="Maximum packet size in the bucket")
    num_connections: int = Field(..., description="Number of unique connections in the bucket")
    source_ip: Optional[str] = Field(..., description="Source IP address")
    source_port: Optional[int] = Field(..., description="Source port number")
    source_mac: Optional[str] = Field(..., description="Source MAC address")
    destination_ip: Optional[str] = Field(..., description="Destination IP address")
    destination_port: Optional[int] = Field(..., description="Destination port number")
    destination_mac: Optional[str] = Field(..., description="Destination MAC address")
    source_key: str = Field(None, description="Unique key for the source endpoint")
    destination_key: str = Field(None, description="Unique key for the destination endpoint")
    tcp_cwr_count: int = Field(..., description="Count of TCP CWR flags")
    tcp_ece_count: int = Field(..., description="Count of TCP ECE flags")
    tcp_urg_count: int = Field(..., description="Count of TCP URG flags")
    tcp_ack_count: int = Field(..., description="Count of TCP ACK flags")
    tcp_psh_count: int = Field(..., description="Count of TCP PSH flags")
    tcp_rst_count: int = Field(..., description="Count of TCP RST flags")
    tcp_syn_count: int = Field(..., description="Count of TCP SYN flags")
    tcp_fin_count: int = Field(..., description="Count of TCP FIN flags")
    tcp_syn_ratio: float = Field(..., description="Ratio of SYN packets to total packets")
    tcp_ack_ratio: float = Field(..., description="Ratio of ACK packets to total packets")
    modbus_response_count: int = Field(..., description="Count of Modbus responses in the bucket")
    modbus_response_ratio: float = Field(..., description="Ratio of Modbus responses to total packets")
    avg_modbus_response_code: Optional[float] = Field(None, description="Average Modbus response code")
    modbus_response_present: int = Field(..., description="Indicator if Modbus response is present (1) or not (0)")
